version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  server:
    image: node:18
    working_dir: /app
    command: node server/index.js
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '3001:3001'
    depends_on:
      - redis
  client:
    image: node:18
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - CI=true
    depends_on:
      - server
volumes:
  redis-data:
