name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --omit=dev
      - run: zip -r backend.zip server package.json package-lock.json
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 cp backend.zip s3://${{ secrets.EB_S3_BUCKET }}/${{ github.sha }}.zip
      - run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=${{ secrets.EB_S3_BUCKET }},S3Key=${{ github.sha }}.zip
          aws elasticbeanstalk update-environment --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label ${{ github.sha }} \
            --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=REDIS_URL,Value=${{ secrets.REDIS_URL }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: aws-amplify/amplify-hosting-deploy@v1
        with:
          app-id: ${{ secrets.AMPLIFY_APP_ID }}
          branch-name: ${{ secrets.AMPLIFY_BRANCH }}
          src-dir: build
