name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync static assets
        run: |
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET }} --delete --cache-control 'max-age=31536000,public,immutable' --exclude index.html
          aws s3 cp build/index.html s3://${{ secrets.S3_BUCKET }}/index.html --cache-control 'no-cache, no-store, must-revalidate' --content-type 'text/html'
          aws s3 cp build/index.html s3://${{ secrets.S3_BUCKET }}/404.html --cache-control 'no-cache, no-store, must-revalidate' --content-type 'text/html'
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
